version: '3.8'

services:
  frontend:
    image: phani5566/fullstack-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    image: phani5566/fullstack-backend:latest
    ports:
      - "8978:8978"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
